### ISSUE TITLE
Escaping from the first plague doctor encounter results in the player being unable to move

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#100]
**Severity**
Major

**Describe the bug**
The plague doctor runs toward the player, but is walled off, so he can't actually kill the player. The player is unable to move anymore.

**To Reproduce**
1. Launch the tutorial level.
2. Progress until you reach the second rat hole (the one with the slime on the other side).
3. Enter the hole (TWSS).
4. Once on the other side, enter the rat hole once more.

**Expected behavior**
The player shouldn't be able to re-enter the hole and the cutscene should occur.

**Screenshots**
[gif](https://media.giphy.com/media/1qXINFRpJ7yNuRJ7TS/giphy.gif)

**Comment by Mottelz** [comment]
I didn't need to try to escape in order to not trigger the Plague Doctor attack. 
![output](https://user-images.githubusercontent.com/5210066/49172277-959d3600-f30e-11e8-9a90-316b21be7926.gif)

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.49
