### ISSUE TITLE
The enemy puppet deals no damage when using its dash attack

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#112]
**Severity**
Major

**Build**
v0.2.1.44

**Describe the bug**
When the puppet charges the player, the player receives no damage.

**To Reproduce**
1. Launch level 1
2. Progress until you encounter a puppet
3. Approach the puppet and allow it to dash into you

**Expected behavior**
The player loses health when attacked by the puppet.

**Additional context**
After further testing, dash attacks only damages the plague doctor when on the slope (i.e. different altitudes) like so:

![screenshot 38](https://user-images.githubusercontent.com/10624460/49104421-ed269d80-f24b-11e8-9d8c-8188699a15ac.png)

**Comment by Jerjerzanne** [comment]
This should be fixed on the eai-dev branch. Will update issue when these fixes are added to the release.

**Comment by Jerjerzanne** [comment]
v0.2.1.45 pushed. Awaiting review.

**Comment by TheMelanieJoy** [comment]
Fix confirmed in build v0.2.1.45. Closing the issue as resolved!

**Comment by TheMelanieJoy** [comment]
Reopening issue because it now occurs on build v0.2.2.51

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.3.1.56. Closing once more
