### ISSUE TITLE
Enemy puppet behaves erratically

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#115]
**Severity**
Major:

**Build**
v0.2.1.44

**Describe the bug**
Already a known issue. The puppet jumps like crazy and twitches left and right as if it were on cocaine.

**To Reproduce**
1. Launch level 1.
2. Progress until you encounter a puppet.
3. Enjoy the show.

**Expected behavior**
The enemy's jumping should be limited, if at all, and shouldn't be so twitchy.

**Comment by Jerjerzanne** [comment]
Behavior should be fixed on eai-dev. Will update when this gets into the next release.

**Comment by Jerjerzanne** [comment]
v0.2.1.45 pushed. Awaiting review

**Comment by TheMelanieJoy** [comment]
The puppet's AI is still a little odd when near slopes: https://i.giphy.com/media/4NrGuWuNOMKxAjEol1/giphy.webp

@Jerjerzanne I will keep the bug open, but you can close it if you feel it is not an issue.

**Comment by StupidChris** [comment]
Closing for deprecation
