### ISSUE TITLE
Rat AI bugs

### ISSUE THREAD

**Issue by RennXD** [TeamViral/ViralCurse#117]
**Severity**
Major: 

Build
v0.2.1.44

**Describe the bug**
Only does movement not attack.

**To Reproduce**
1. Go to "Start Game"
2. Move around as Plague Doctor
3. Get close to a rat and dance with them.

**Expected behavior**
Rat should attack when its within range. Additionally they can do FUSION when player 

**Screenshots**
https://gyazo.com/2a46d49cb096a64482d01266e6240bc6
https://gyazo.com/8953b3e0866898c7916bd5c1b4ccb370

**Comment by StupidChris** [comment]
Seemingly fixed, marking as resolved
