### ISSUE TITLE
Enemy puppet death

### ISSUE THREAD

**Issue by RennXD** [TeamViral/ViralCurse#118]
**Severity**
* Minor: 

**Describe the bug**
Enemy puppet does the moon walk when it dies.

**To Reproduce**
1. Start Game
2. Progress until you see enemy puppet
3. Kill enemy puppet and watch his moon walk.

**Expected behavior**
Puppet should die on spot.

**Screenshots**
https://gyazo.com/a1356b254ece8e362e3a33e81d1595e7

**Comment by Jerjerzanne** [comment]
Its probably an issue with the material or velocity being preserved.

**Comment by StupidChris** [comment]
definitely the material, I noticed it as well. It happens during the dash, you need to make sure the death material gets reset

**Comment by StupidChris** [comment]
Closing for deprecation
