### ISSUE TITLE
Death possession

### ISSUE THREAD

**Issue by RennXD** [TeamViral/ViralCurse#119]
**Severity**

Critical: 

Build
v0.2.1.44

**Describe the bug**
If your hp runs out, and you, as a plague doctor kills another plague doctor that lobs projectiles only. If both player and monster dies at the same time, player takes over the dead plague doctor body.

**To Reproduce**
1. Start Game.
2. Progress the game until player reach the bottom right floor.
3. Encounter Throwing Plague Doctor. 
4. Start a flying canes fight and die together.
5. To be more specific, hit enemy with throwing attack 4 times and player should have 10 hp left.
6. Use one more throwing attack and see result.

**Expected behavior**
Should not be able to possess dead body.

**Screenshots**
![bug death throws](https://user-images.githubusercontent.com/26392831/49112964-3d105f00-f262-11e8-86ad-d23a99f41ff7.png)

https://gyazo.com/872eac9def235e47ef48cf802d707e98

**Comment by RennXD** [comment]
Still persist in build v0.2.1.45

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.1.44
