### ISSUE TITLE
Combat System/ Collision bug

### ISSUE THREAD

**Issue by RennXD** [TeamViral/ViralCurse#120]
**Severity**
* Major: 
Build
v0.2.1.45

**Describe the bug**
Avoid enemy attacks while being on top of a monster

**To Reproduce**
1. Encounter non jumping enemies.
2. Jump on top of them.
3. Start Beating the shit of them

**Expected behavior**
Should not be able to attack while being on top of a monster

**Screenshots**
https://gyazo.com/bfc273f936fcd2b4819f85e0e7c518c9
https://gyazo.com/060277a9d6dd0e035f65af1f3954f153
https://gyazo.com/fba914ac2415abe567f3465f6aa81bef?token=9bff31869bebd129f8ea08529e3af4d2

Weird movement bug too 
https://gyazo.com/312e404e1340b5999ae8bf8cca11762e

**Comment by Jerjerzanne** [comment]
There are multiple ways to solve this issue:
- [ ] You could bounce on the head, making it difficult to stay on the head of an enemy.
- [ ] Enemies melee attack's hitboxes could cover their heads, hitting the player off with the knockback. 
Let me know what makes the most sense.

**Comment by StupidChris** [comment]
I think you shouldn't be able to be on an enemy's head at all. Either you could bounce clear off an enemy's head, or you could go straight through using a platform effector and then be able to walk out

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.51
