### ISSUE TITLE
Buff Guy TOO BUFF

### ISSUE THREAD

**Issue by RennXD** [TeamViral/ViralCurse#121]
**Severity**
Select the severity label that best applies to the issue:
* Critical: 
Build
v0.2.1.45

**Describe the bug**
Buff guy too buff so he cannot go up from the bottom floor. 

**To Reproduce**
1. Become Buff Guy
2. Try to jump up to the platform
3. See error

**Expected behavior**
Buff guy did not skip leg day, so he should be able to climb back up to the middle floor

**Screenshots**
Area
![buffguystuck](https://user-images.githubusercontent.com/26392831/49115062-b8c0da80-f267-11e8-994d-5b9aa3ba2ee3.png)

https://gyazo.com/bce3067ac5de5245825f1627aac0653f

UPDATE
It is possible to go back to middle floor.
You must crouch under the platform then jump up.

https://gyazo.com/7a7251d888ffeba49eb25ffbca0596c9

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.1.47
