### ISSUE TITLE
The hammer wielder's crouch-walk animation does not look like it is supposed to.

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#123]
**Severity**
Trivial

**Build**
v0.2.1.45

**Describe the bug**
The hammer wielder's crouch-walk animation does not animate as expected. Rather than taking small lunge-like steps, the hammer wielder spreads his legs.

**To Reproduce**
1. Launch level 1.
2. Progress until you encounter the hammer wielder.
3. Allow the hammer wielder to kill you and take possession of it.
4. Crouch and walk.

**Expected behavior**
The hammer wielder crouch-walks by lifting one leg at a time as shown in the [wiki](https://github.com/TeamViral/ViralCurse/wiki/Enemies#the-hammer-e).

**Comment by Jerjerzanne** [comment]
Probably fucked up the animator, will have a look tomorrow morning.

**Comment by TheMelanieJoy** [comment]
Crouch-walk looks fine visually, but the hammer-wielder's crouch-walking is now inconsistent. There are times where it would just be walking in place or very slowly
