### ISSUE TITLE
When fighting two plague doctors, the player still lives after reaching 0 HP

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#138]
**Severity**
Minor

**Build**
v0.2.1.45

**Describe the bug**
When fighting the two plague doctors, there are two observed results:
- As the plague doctor, you can get killed by a plague doctor. As the new doctor, you will still be alive the other one depletes all your HP.
- As the hammer wielder, you will still be alive after reaching 0 HP.

**To Reproduce**
1. Launch level 1.
2. Progress until you encounter two plague doctors (see Screenshot A).
3. Allow the doctors to deplete all of your health.

**Expected behavior**
The player dies as soon as they reach 0 HP.

**Screenshots**
Screenshot A
![image](https://user-images.githubusercontent.com/10624460/49126991-bd9b8380-f293-11e8-9c28-222e49d699a0.png)

![image](https://media.giphy.com/media/OT67QcfcHoVdL1oZn0/giphy.gif)

**Additional context**
This one might be difficult. More information may be needed as I am still unsure of the specific conditions that need to be met to trigger this issue.

**Comment by StupidChris** [comment]
@Jerjerzanne are you playing with how much damage is applied to players? Sounds like the UI just isn't reflecting the true amount of health a player has

**Comment by Mottelz** [comment]
Might have started a related issue on the newest build https://github.com/TeamViral/ViralCurse/issues/150

**Comment by TheMelanieJoy** [comment]
resolved on build v0.2.2.49
