### ISSUE TITLE
Enemies do not follow or attack the player when crouching

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#139]
**Severity**
Minor

**Build**
v0.2.1.45

**Describe the bug**
When the player crouches, an enemy will stop attacking and following them.

**To Reproduce**
1. Launch level 1.
2. Encounter any enemy.
3. Hold the crouch button.

**Expected behavior**
The player may still be attacked while crouching.

**Comment by Jerjerzanne** [comment]
That issue came with the switch to the player controller methods for player detection. I should be able to fix that specific behavior.

**Comment by StupidChris** [comment]
ITS SNEAK MODE

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.49
