### ISSUE TITLE
In level 1, the player can get stuck inside thin platforms

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#140]
**Severity**
Minor

**Describe the bug**
When jumping from under a thin platform in level 1, the player can land inside it. They must keep pressing the jump button to actually jump to a higher platform or crouch walk to drop down from the platform.

**To Reproduce**
1. Launch level 1.
2. Progress through the game until you encounter thin platforms (see Screenshot A).
3. Jump onto the platform.

**Expected behavior**
The player either lands on the platform OR falls back down under the platform. The player can easily jump while on the platform and cannot drop down from the platform.

**Screenshots**
Screenshot A
![image](https://user-images.githubusercontent.com/10624460/49128409-4cf76580-f299-11e8-9617-417d6bd72751.png)

**Additional context**
May be related to #48

**Comment by StupidChris** [comment]
Definitely related to #121

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.49
