### ISSUE TITLE
Pausing while walking does not pause the SFX.

### ISSUE THREAD

**Issue by Arcavexus** [TeamViral/ViralCurse#143]
**Severity**
Minor

**Describe the bug**
Pausing while running will keep playing the walking SFX.

**To Reproduce**
1. Walk around by holding down A or D.
2. While walking, pause with Esc.
3. Audio for walking should keep playing.

**Expected behavior**
The audio should stop as the player pauses the game.

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.49
