### ISSUE TITLE
During a Fight with two Plague Docs I ended up with negative health.

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#150]
**Severity**
Minor

**Build**
v0.2.2.49

**Describe the bug**
On possession mid-fight, the health bar displayed a large negative number. This was only a display issues, I still died after the right number of hits.

**To Reproduce**
(uncertain that these will be consistent)
1. Be a plague doctor.
2. Fight two plague doctors.
3. Have your new one get hit before you possess it.

**Expected behavior**
Should display my actual health.

**Logs**
[Player.log](https://github.com/TeamViral/ViralCurse/files/2625985/Player.log)

**Screenshots**
![screen shot 2018-11-28 at 12 29 18 pm](https://user-images.githubusercontent.com/5210066/49170510-4ce37e00-f30a-11e8-89cf-5046ad89d1c6.png)

**Additional context**
Not sure about how to reproduce this.

**Comment by StupidChris** [comment]
Still can't be reproduced, will be closing for now, feel free to reopen if a way to make it happen reliably is found
