### ISSUE TITLE
Boss door is not apparent after being opened

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#151]
**Severity**
Minor

**Build**
v0.2.2.49

**Describe the bug**
After opening the door that leads to the boss room, there is no way of telling the opened door is there. The user is still prompted to press a key to enter and the door can be entered.

**To Reproduce**
1. Launch level 1
2. Progress until you collected both keys
3. Bring the keys to the skull door

**Expected behavior**
The door itself should still be visible even when opened OR the entrance some kind of glow to it or something that makes it visible

**Screenshots**
![image](https://user-images.githubusercontent.com/10624460/49174800-2545e300-f315-11e8-9538-d201ae43b87a.png)

**Comment by TheMelanieJoy** [comment]
Improvements seen on v0.2.2.51, but it may still be difficult to find for a player that leaves the area (to possess a different enemy for example) and tries to find the door again.

![image](https://user-images.githubusercontent.com/10624460/49212896-18ff6b80-f391-11e8-95db-a9b56491d7fb.png)

**Comment by StupidChris** [comment]
we might just need a frame. We'll deal with this another time though.

**Comment by StupidChris** [comment]
@TheMelanieJoy added a frame, let me know how that looks now

**Comment by TheMelanieJoy** [comment]
Now we can definitely tell that this is the door! Resolved on build v0.3.1.62
