### ISSUE TITLE
Plague Doctor never triggers in tutorial

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#153]
**Severity**
Major

**Build**
v0.2.2.49

**Describe the bug**
In the tutorial, the Plague Doctor never eats the rat/play.

**To Reproduce**
1. Start the tutorial
2. Play until you reach the second rat hole.
3. Walk thru the rat hole.
4. Observe how nothing happens.

**Expected behavior**
The plague doctor should say some stuff and then eat the rat.

**Logs**
[Player.log](https://github.com/TeamViral/ViralCurse/files/2626335/Player.log)

**Screenshots**
![49172277-959d3600-f30e-11e8-9a90-316b21be7926](https://user-images.githubusercontent.com/5210066/49177302-e0bd4600-f31a-11e8-98d2-e15ea8b90ae3.gif)

**Additional context**
I still have full control of the rat. So I can trigger the second ability and sneak back out, but the tile behaves as if there is slime there.

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.51
