### ISSUE TITLE
Enemy puppet gets stuck on an invisible platform in level 1

### ISSUE THREAD

**Issue by Arcavexus** [TeamViral/ViralCurse#155]
**Severity**
Trivial

**Build**
v0.2.2.49

**Describe the bug**
The first puppet encountered in level 1 can run into an invisible platform and stay stuck there until the player moves to a different location.

**To Reproduce**
1. Find the first puppet in level 1.
2. Dodge his attack and keep it moving.
3. It eventually runs into the invisible platform above the player and is stuck there for a while.

**Expected behavior**
The puppet should not hit an invisible platform.

**Screenshots**
![image](https://user-images.githubusercontent.com/24647619/49178500-e4060100-f31d-11e8-9f8b-7fd183a18bde.png)

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.51
