### ISSUE TITLE
Possessing an enemy on top of an another enemy pushes that enemy out of the level

### ISSUE THREAD

**Issue by Arcavexus** [TeamViral/ViralCurse#157]
**Severity**
Trivial

**Build**
v0.2.2.49

**Describe the bug**
Possessing an enemy that is overlapped onto another enemy will push that enemy out of the map.

**To Reproduce**
1. Go to indicated zone in level 1 (see picture 1).
2. Have muscle guy and plague doc chase you and overlap on top of each other next to the stairway.
3. Submit or die to muscle guy.
4. Plague doc will be pushed out of the map.

**Expected behavior**
Plague doc should not be pushed out of the map.

**Screenshots**
![image](https://user-images.githubusercontent.com/24647619/49179282-fe40de80-f31f-11e8-9215-b1443da28716.png)
![image](https://user-images.githubusercontent.com/24647619/49179470-5a0b6780-f320-11e8-9e89-441788128811.png)

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.51
