### ISSUE TITLE
Reaching the boss door with two keys might fill one slot and lock the player out of putting more keys in

### ISSUE THREAD

**Issue by Arcavexus** [TeamViral/ViralCurse#158]
**Severity**
Major

**Build**
v0.2.2.49

**Describe the bug**
Reaching the boss door with 2 keys (without having visited it beforehand) will only fill one slot of the door and lock the player out of putting more keys in. Also, no dialogue box is triggered.

There is an unknown condition to this bug occurring as simply speedrunning through each key and then reaching the boss door will open it normally.

**To Reproduce**
1. Obtain two keys without visiting the boss door beforehand.
2. ??? (Some unknown condition)
3. Reach the boss door.

**Expected behavior**
Both keys should be inserted and the boss door should open. Also, the dialogue box should trigger beforehand (or during).

**Screenshots**
![image](https://user-images.githubusercontent.com/24647619/49180404-858f5180-f322-11e8-8029-b7411b74ca2f.png)

**Comment by StupidChris** [comment]
Not able to repplicate in new (upcoming) build, I'd like more feedback

**Comment by StupidChris** [comment]
Closing for now as no one is able to reproduce. If it appears again or a solid way to make it happen is found, feel free to reopen
