### ISSUE TITLE
Having an enemy on a jump-through platform above you stops you from reaching that platform normally

### ISSUE THREAD

**Issue by Arcavexus** [TeamViral/ViralCurse#159]
**Severity**
Minor

**Build**
v0.2.2.49

**Describe the bug**
Having an enemy (in this case, the puppet) on a platform above you stops you from reaching that platform as a plague doctor.

**To Reproduce**
1. Go to the indicated spot (see picture 1) as plague doc.
2. Get the puppet to jump on the platform above you.
3. Try jumping through the platform. The puppet will prevent you from doing so and you will have a hard time trying to kill it.

**Expected behavior**
Jumping through a platform with an enemy above you should not affect your jump height.

**Screenshots**
![image](https://user-images.githubusercontent.com/24647619/49181130-8cb75f00-f324-11e8-9013-7cf3e928f865.png)

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.51
