### ISSUE TITLE
Impossible to get through a tunnel with an enemy on the other side without dying

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#160]
**Severity**
Minor

**Build**
v0.2.2.49

**Describe the bug**
When crouching through a tunnel with an enemy on the other side, the enemy will block the way out and attack you (and knock you back) as you try to push through. This makes it impossible to get out of the tunnel without dying.

**To Reproduce**
1. Launch level 1.
2. Reach the tunnel indicated in Screenshot A **without** killing the plague doctor nearby
3. Once in the tunnel, attempt to re-emerge from the entrance you went through

**Expected behavior**
The player should be given some space to actually come out and have a chance to fight.

**Screenshots**
Screenshot A
![location](https://user-images.githubusercontent.com/10624460/49102663-6a9bdf00-f247-11e8-90df-ff5f1e7c5792.png)

![cornered](https://user-images.githubusercontent.com/10624460/49181592-c6d53080-f325-11e8-9fee-f4bf51c248de.gif)

**Comment by Jerjerzanne** [comment]
Yeah that is an issue. I want to add a behavior that will make them return in place after a while, or we could limit aggro to only what's in front of the AI.

**Comment by StupidChris** [comment]
I think altering the level would be the fastest and easiest solution here. We could raise the tunnel up one block

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.51
