### ISSUE TITLE
Buff Guy Too Buff again

### ISSUE THREAD

**Issue by RennXD** [TeamViral/ViralCurse#162]
**Severity**
Minor

**Build**
 v0.2.2.49

**Describe the bug**
Crouch-walking under a platform results in the hammer-wielder being stuck in crouching position.
Buff Guy squatted too much and he is now stuck.

**To Reproduce**
1. Go to Area in screenshot as Buff Guy.
2. Crouch-walk onto or under the platform.
3. See error.

**Expected behavior**
Buff guy should be able to jump back up. He did not skip legs day for a reason.

**Screenshots**
![buffguysquat4ever](https://user-images.githubusercontent.com/26392831/49186020-60560f80-f331-11e8-8e86-c71f2a27036d.png)

https://gyazo.com/8ce39b5b2310fb2f32f22c9072aea085

**Additional context**
Related to #121

**Comment by StupidChris** [comment]
Not related to #121, actually related to the fix for #113. Ill add a platform check for this corner case

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.51
