### ISSUE TITLE
Rat Gameplay Punishing - Mentioned in Discord

### ISSUE THREAD

**Issue by RennXD** [TeamViral/ViralCurse#163]
**Is your feature request related to a problem? Please describe.**
Many scenarios played as a rat becomes annoying and punishing. Rats should be able to navigate properly without always dying too fast.

**Screenshots**
![ratareas](https://user-images.githubusercontent.com/26392831/49186271-20dbf300-f332-11e8-9072-d1ca7fe57679.png)

Green Area: Rat get killed instantly if it keeps going straight.
https://gyazo.com/37379b03cf66f4263f082cb4c8fa99e1

Blue Area: Not sure how a Rat can bypass all these enemies
https://gyazo.com/4e1b94d94b415672fc7f609ef5784d0f
https://gyazo.com/8c7cd54ff836f387584832caffffdd60
By pass by using the head over collision
https://gyazo.com/7251b221dad09b13e771c2d3c8018a7e

Encounter new enemies
https://gyazo.com/317d20b79fe1a40b52b84e60db1d8453
https://gyazo.com/c88936833b207d0d963c45e1b9fca3f9

Red Area: Not sure how to progess this area
https://gyazo.com/0cd8ec94da0f05e98e25be28cf1847fc
https://gyazo.com/356d20b966ced1e456a3f9572b6360af

**Describe the solution you'd like**
Solutions mentioned are increase rat's hp to 50 and puppet to 100 hp.

**Comment by TheMelanieJoy** [comment]
Implemented on build v0.2.2.51. The rat (and the puppet) is now a more viable enemy to possess since it won't die as quickly and does more damage
