### ISSUE TITLE
Hammer-wielder's crouch-walk is inconsistent

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#164]
**Severity**
Minor

**Build**
v0.2.2.49

**Describe the bug**
When crouch-walking as the hammer-wielder, there are times where you would just be walking in place or very slowly.

**To Reproduce**
1. Launch level 1
2. Take possession of the hammer-wielder
3. Crouch-walk

**Expected behavior**
Crouch-walking is always smooth and consistent.

**Screenshots**
![crouch-walk_in_place](https://user-images.githubusercontent.com/10624460/49188950-8633e200-f33a-11e8-9509-b030874ffa5d.gif)

**Additional context**
May be related to #162

**Comment by StupidChris** [comment]
Not related to #162, but to something I attempted to recreate pixel perfect movement. Its causing too many issues so Ill remove it tonight.

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.51
