### ISSUE TITLE
Inconsistent damage on spider projection

### ISSUE THREAD

**Issue by RennXD** [TeamViral/ViralCurse#185]
**Severity**

* Minor: 

**Build**
 v0.3.1.56.

**Describe the bug**
Spider projectiles does 15, 30 and sometimes 60 for some reasons.

**To Reproduce**
1. Become spider
2. Get hit by enemy spiders.
3. See error

**Expected behavior**
Damage should be consistent

**Screenshots**
https://gyazo.com/162a814660f53804376677c40b35c147

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.3.1.62
