### ISSUE TITLE
Unity version in readme

### ISSUE THREAD

**Issue by guiray** [TeamViral/ViralCurse#192]
I would like to see the Unity version used in the read me. When Wwise will be integrated I will do the same.

**Comment by StupidChris** [comment]
Is the *readme* the best place for that? I'm down to have it somewhere but I think it should just be convenient and hopefully automatized. If you just need quick access to it, I can make a short script that dumps the version to the disk somewhere.

**Comment by guiray** [comment]
Doesn't have to be on the read me, I just thought that it is fairly easy to go on the main repo page and see that info. But yeah whatever you feel is easier!

For my use it's to validate I open the project in the right version, same for Wwise

**Comment by StupidChris** [comment]
Unity Hub will notify you if you open the project in the wrong version though

**Comment by guiray** [comment]
👍
