### ISSUE TITLE
Design Tutorial level characters

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#2]
Design the sprites and animations for tutorial characters

- [x] Enemy: Rat (@TheMelanieJoy)
  * Ability: burrows in a hole in the wall
  * Attack: bites, razor tail whip (attacks backwards)
  * Size should be half a tile.
- [x] Enemy: Goblin/Humanoid (@RennXD)
  * Larger and jumps higher than the rat
  * Two tiles high by 1 tile wide
  * Has a spear it can use to poke, and throw.
  * Should be designed for reusability and recoloring
- [x] Character (first possession): Humanoid (@TheMelanieJoy)
  * Crawling, dying
  * Size is 2x2 tiles
- [x] Character: Protagonist (@RennXD)
  * Based on concept art, but ultimately open for interpretation
  * Should be 1x1 tiles in size

**Comment by JeffRayGun** [comment]
@Arcavexus I added some specifications for the characters, especially tile size specifications

**Comment by StupidChris** [comment]
Characters in themselves are designed, needing animations however, covered in #34, so I'm closing this one
