### ISSUE TITLE
Design Tileset

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#3]
Design the tutorial level tileset

* [x] Background
* [x] Surface floor (surface that the characters stand on)
* [x] Floor beneath the surface (similar to how Minecraft has dirt tiles under the grass)
* [x] Wall
* [x] Inward corners
* [x] Outward corners
* [x] Wall with a hole (for the rat)
* [x] *Door/gate (on hold)*
* [x] *Torch (on hold)*
* [x] *Lever (on hold)*
* [x] *Jump-through platform (on hold)*

**Comment by StupidChris** [comment]
Probably a good ideas that you guys have a look at the [Unity Tilemaps](https://docs.unity3d.com/Manual/Tilemap.html), as this is how the art will be integrated into the game, and the format we will need it in.

**Comment by felixyf0124** [comment]
[Tileset.zip](https://github.com/TeamViral/ViralCurse/files/2498625/Tileset.zip)
done with wall, wall with hole, wall with torch, torch only(background transparent), door (1 unit, 16x16), gate(2 unit, 32x16), lever (on the ground)

**Comment by JeffRayGun** [comment]
@Arcavexus As requested by Chris, here's the official list of non-character assets that will be needed for the tutorial level:

- [ ] Lever
- [ ] Door (Should be 1 tile wide and 3 tiles high, to allow the largest monsters to pass through. View from the side.)
- [ ] Gate (1 tile wide and 3 tiles high. View from the side)
- [ ] Slope tiles, left facing and right facing (could be straight up slopes, or stairs)
- [ ] _Diagonal ceiling corner tiles (optional, could be used to spruce up the look of the level)_
- [ ] Some furnishing for the cell room the player starts in.

Furthermore, here's the tileset that I'm using for creating level sketches. You could use that for inspiration for the tileset, if you'd like.
![level_tiles](https://user-images.githubusercontent.com/32502702/47261696-ee251c00-d4a2-11e8-98ec-c3a8a0f23bb1.png)

For the half tiles, I'm only planning to use the ones with a hole on the bottom half, so you can ignore the rest.

**Comment by felixyf0124** [comment]
![gate_sheet](https://user-images.githubusercontent.com/22183052/47535065-ca3d4e00-d887-11e8-99bb-84d03e665217.png)
![gate_sheet_x4](https://user-images.githubusercontent.com/22183052/47535066-cad5e480-d887-11e8-9448-bf1d2482699a.png)

**Comment by StupidChris** [comment]
Pretty much complete, marking as closed
