### ISSUE TITLE
Complete GDD

### ISSUE THREAD

**Issue by StupidChris** [TeamViral/ViralCurse#37]
The Game Design document needs to be completed. I've already filled out what each section needs and most of them are basically adaptations of the wiki. It's just best if each section is done by that team's lead. As always, I'm around if you have any questions. (aside from Friday 5pm until Saturday at 6:45pm) - Mottel 

- [x] Fill in Art section. (@Arcavexus )
- [x] Fill in Level Design section (@JeffRayGun )
- [x] Fill in Technology & Software Architecture (@StupidChris )
- [x] Fill in Meeting Summaries/Change Log (@Mottelz )
- [x] Design a simple game logo (@TeamViral/art )

**Comment by Mottelz** [comment]
Here's a link to the GDD https://docs.google.com/document/d/1oP9FG2ZbZiQ4rpq-T3dAsIYFZ2vpQ_z-xa0dOzQMMPs/edit#heading=h.4d34og8

@StupidChris @Arcavexus @JeffRayGun

**Comment by Mottelz** [comment]
@StupidChris I want to leave it open until we get the video done and added to the presentation.

**Comment by StupidChris** [comment]
Done fuckaz
