### ISSUE TITLE
Get Level 1 Audio & Music

### ISSUE THREAD

**Issue by StupidChris** [TeamViral/ViralCurse#38]
Pretty self explanatory, but music is gonna be needed, assigning @TeamViral/audio to this, figure it out between you guys

- [x] Menu music
- [x] Tutorial/Level1 music 

**Remaining tasks:**
- **Mottel**
- [x] Standard walk
- [x] Standard possession
- **Simon**
- [x] Doctor attack
- [x] Doctor Die
- [x] Doctor Take Damage
- **Felix**
- [x] Rat Take Damage
- [x] Gate lifting

**Comment by Mottelz** [comment]
I found the music for the menu and for level one. We still need to finalize it and work on the audio sound effects.

**Comment by StupidChris** [comment]
Looks done here
