### ISSUE TITLE
Estabilsh Style Guides

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#4]
We need to setup some basic style guides for everyone to follow. 

- [x] Code style guide (@StupidChris ) 
This will include rules to follow for scripts and basic comment styles which will work with doxygen. 
- [x] Art style guide (@Arcavexus ) 
This will include the colour pallet for the game and a basic description of how a possessed character differs from unpossessed. 
- [x] Story style guide (@Mottelz )
This will include a basic narrative outline and will make all of the art choices made so far make sense.
- [x] Mechanics design guide (@JeffRayGun ) 
This will include mainly design constraints. For example, "all levels are 50x50 tiles," "all characters have one unique move," etc.

### All guides should also include the principals that those team leaders think are important and anything else you want to include.

**Comment by StupidChris** [comment]
Just want to add a note here:

For simplicity's sake of having everything at the same place if possible, setup your document as a [Markdown](https://guides.github.com/features/mastering-markdown/) (.md) file and upload it to the ViralCurse/Design folder in the repository. You should probably also use the 'design' branch to do your edits.

**Comment by StupidChris** [comment]
Art integration pipeline seemingly implemented in #9, probably still needing artistic direction though

**Comment by StupidChris** [comment]
Only missing a more complete story guidelines from @Mottelz

**Comment by StupidChris** [comment]
Seemingly completed by everyone, closing.
