### ISSUE TITLE
Player gameObject slides down Slopes in level

### ISSUE THREAD

**Issue by Jerjerzanne** [TeamViral/ViralCurse#43]
**Severity**
Minor

**Describe the bug**
When the player goes on uneven terrain, he will begin to slide down if the player does not move.

**Expected behavior**
The player should not slide down slopes.

**Screenshots**
![sliding](https://user-images.githubusercontent.com/24967824/47610318-584c3c80-da20-11e8-9435-eac473984fe0.gif)

**Comment by StupidChris** [comment]
Adding a physics material with more friction to the ground should probably do the trick, will try it out later.

**Comment by StupidChris** [comment]
Fixed in [v0.1.2.6](../releases/tag/v0.1.2.6), let me know if that's works fine for you :)
