### ISSUE TITLE
Jump does not consistently work

### ISSUE THREAD

**Issue by Arcavexus** [TeamViral/ViralCurse#46]
**Severity**
Major

**Describe the bug**
When pressing (Input.GetKeyDown) the Jump button (presumed to be W or Up arrow) the character does not always jump.

**To Reproduce**
Press the jump button repeatedly.

**Expected behavior**
The character should jump every time the Jump button is pressed if he is on the ground.

**Comment by StupidChris** [comment]
Might be related to #44, will take a look

**Comment by StupidChris** [comment]
@Arcavexus attempted fix in [v0.1.2.4](../releases/tag/v0.1.2.4), let me know if it works better now

**Comment by StupidChris** [comment]
[v0.1.2.5](../releases/tag/v0.1.2.5) should also work for this

**Comment by StupidChris** [comment]
@TeamViral/qa can we get other people to chime in here, this is being reported as bot tixed but im absolutely unable to make it work here. Every time I press the jumo button when the character is on the floor he jumps reliably.

**Comment by Mottelz** [comment]
Here's my log for when it happened to me. It's not a reliable bug. It only shows up sometimes.
[Player.log](https://github.com/TeamViral/ViralCurse/files/2523210/Player.log)

**Comment by StupidChris** [comment]
This isn't gonna be a problem causing exceptions, it's just being unreliable. I'm not able to reproduce this at all here locally. Not too sure how to proceed.

**Comment by StupidChris** [comment]
Possibly fixed in [v0.1.2.6](../releases/tag/v0.1.2.6) (for real this time), I'd like confirmation though.

Problem is that the jump press was queried in FixedUpdate. Which is bad.

**Comment by Jerjerzanne** [comment]
Jump feels responsive to me on v0.1.2.6,

**Comment by Arcavexus** [comment]
Resolved in latest build.
