### ISSUE TITLE
Player is in a falling state when standing on a lever

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#47]
**Severity**
Minor

**Describe the bug**
When standing on top of a lever, the player plays the falling animation. The player is unable to jump, crouch, or use any of their abilities.

**To Reproduce**
1. Launch the tutorial level.
2. Progress through the game until you reach the second lever.
3. Jump to the top of the lever.

**Expected behavior**
The player is in an idle state when on top of the lever OR the player cannot be on the lever (the player lands on the ground and stands behind, similar to how he stands behind the bone decor).

**Screenshots**
![video3](https://user-images.githubusercontent.com/10624460/47610698-d5c87a80-da29-11e8-909f-2c525acdc259.gif)

**Comment by StupidChris** [comment]
Oh, good catch. Yeah, I think Ill make them stay behind it. Or in front? Not sure which would look best. I dont think we should be able to stand on levers though.

**Comment by StupidChris** [comment]
Also, upgrading to Major since this can softlock the player

**Comment by StupidChris** [comment]
@TheMelanieJoy attempted fix in [v0.1.2.4](../releases/tag/v0.1.2.4), let me know if this is fine

**Comment by StupidChris** [comment]
[v0.1.2.5](../releases/tag/v0.1.2.5) should also work for this

**Comment by TheMelanieJoy** [comment]
Fix confirmed on build 0.1.2.5
