### ISSUE TITLE
Jumping under a thin platform may result in landing inside the platform

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#48]
**Severity**
Minor

**Describe the bug**
When jumping under a thin platform, the player can land inside it. If the player walks, they will fall off the platform.

**To Reproduce**
1. Launch the tutorial level.
2. Progress through the game until you encounter a thin platform.
3. Fall off the platform and place yourself underneath it.
3. Hold the jump button. The timing of the jump hold must be right. If you jump too high, you land on the platform.

**Expected behavior**
The player either lands on the platform OR falls back down under the platform.

**Screenshots**
![video4](https://user-images.githubusercontent.com/10624460/47610934-4a51e800-da2f-11e8-8804-b332c9ec6f70.gif)

**Comment by StupidChris** [comment]
This one might be tricky. The platforms are actually a Unity implementation. I could make the collider smaller, but then it risks having the playet jump through it because its too thin. Ill look at the docs if anything can help.

**Comment by StupidChris** [comment]
Didn't mean to close in the commit, but this is possibly fixed in [v0.1.2.5](../releases/tag/v0.1.2.5), I'm unable to clip through them anymore, though that might just be me being horrible at this.
