### ISSUE TITLE
Design Tutorial Level 

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#5]
Implement tutorial level

- [x] Level narrative (@Mottelz)
- [x] Layout level (@TeamViral/leveldesign)
- [x] Build level in the game (@TeamViral/code)
- [ ] Test level ( @TeamViral/qa )

**Comment by StupidChris** [comment]
Level is built, waiting on full completion of the controllers to test

**Comment by StupidChris** [comment]
Looks done to me
