### ISSUE TITLE
Attacks Queue While Crouched. 

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#55]
**Severity**
Minor

**Describe the bug**
Cannot attack while crouched, but the attack seems to be stored in queue so that when I stand the attack immediately happens. 

**To Reproduce**
1. Press and hold the down arrow.
2. Press either Z or X

**Expected behavior**
I figure it should either stand me up or allow me to attack crouched. 

**Logs**
[Player.log](https://github.com/TeamViral/ViralCurse/files/2530633/Player.log)

**Comment by StupidChris** [comment]
This is intended behaviour, otherwise we'd need crouched attack animations

**Comment by Mottelz** [comment]
@StupidChris why does it queue though?

**Comment by StupidChris** [comment]
Ah probably an artefact from the animator, it doesnt actually attack, just animates. Thatd a bug.

**Comment by StupidChris** [comment]
Attempted fix in [v0.1.2.7](../releases/tag/v0.1.2.7)

**Comment by Mottelz** [comment]
Tested and it's fixed.
