### ISSUE TITLE
Cannot see lever from the spot I should

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#56]
**Severity**
Minor

**Describe the bug**
The second lever (the one we should be able to shoot at) cannot be seen when standing at the edge of the platform to hit it from.

**To Reproduce**
1. Stand at the edge of the platform.
2. Look right.

**Expected behavior**
I should be able to see the thing I need to hit.

**Logs**
[Player.log](https://github.com/TeamViral/ViralCurse/files/2530660/Player.log)

**Screenshots**
![screen shot 2018-10-30 at 12 39 01 pm](https://user-images.githubusercontent.com/5210066/47735180-611c5880-dc42-11e8-9335-3953f1f81369.png)

**Comment by StupidChris** [comment]
Discussed on Discord, its visible from below, Ill see about adding it if possible during level scripting

**Comment by StupidChris** [comment]
Attempted fix in [v0.1.2.7](../releases/tag/v0.1.2.7)

**Comment by Mottelz** [comment]
Tested and it's fixed.
