### ISSUE TITLE
Walls are occasionally sticky

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#57]
**Severity**
Major

**Describe the bug**
While falling, you can walk into a wall to stay in the air.

**To Reproduce**
1. Stand on platform
2. Walk off platform
3. Walk back towards platform while falling.

**Expected behavior**
Player should keep falling

**Logs**
[Player.log](https://github.com/TeamViral/ViralCurse/files/2531718/Player.log)

**Screenshots**
![output](https://user-images.githubusercontent.com/5210066/47752042-cdf71900-dc69-11e8-82c2-ac2fe7d1d1b8.gif)

**Additional context**
- Sometimes if you jump upwards it doesn't happen and the moment you let go of the button it stops. 
- Walls also seem to cause some friction, which doesn't allow players to jump as high as they need to.

**Comment by StupidChris** [comment]
This is trivial at best, might not resolve for tutorial

**Comment by StupidChris** [comment]
Attempted fix in [v0.1.2.7](../releases/tag/v0.1.2.7)

**Comment by Mottelz** [comment]
Tested and it is fixed.
