### ISSUE TITLE
Setup Character Controller

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#6]
Setup the Character Controller in game

- [x] Setup main Player controller class
- [x] Setup Movement Controller base class
- [x] Setup Attack Controller base class

**Comment by StupidChris** [comment]
Ideally would need one workable character to setup the first point, and two for the second, but we can probably work around it. Point three is rather moot, importing in Unity is drag and drop. I just need to know what the standard format @TeamViral/art  will be using to setup the sprite sheets accordingly.

**Comment by StupidChris** [comment]
Movement and attack controllers functional, just missing correct handling of death and possessions in PlayerController

**Comment by StupidChris** [comment]
All done
