### ISSUE TITLE
Throwing a projectile towards the second lever causes involuntary camera movement

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#60]
**Severity**
Minor

**Describe the bug**
In the tutorial, from the first gate onward, when throwing a projectile towards the second lever (that is, on the higher platform and facing right), the camera momentarily pans to the right.

**To Reproduce**
1. Launch the tutorial level.
2. Progress through the level until the first gate is opened.
3. As the plague doctor, stand at the gate.
4. Throw a projectile to the right.
(Optional) 4.a. Spam the projectile button for a more apparent observation of the issue.
5. Wait a few second until the error is observed.

**Expected behavior**
Throwing a projectile towards the second lever does not affect camera movement.

**Screenshots**
![projectile_camera](https://user-images.githubusercontent.com/10624460/47804645-b96b5d00-dd0b-11e8-926d-7e5f01011f52.gif)

**Comment by StupidChris** [comment]
Possibly fixed in [v0.1.3.18](../releases/v0.1.3.18)

**Comment by StupidChris** [comment]
Marking as resolved here
