### ISSUE TITLE
Changing facing direction while throwing projectile causes the projectile to not move

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#61]
**Severity**
Minor

**Describe the bug**
When changing the direction that you are facing while throwing a projectile, it will not move and just float next to you. The projectile can be nudged to either move at a slow pace or just simply fall. If done while in the air, the projectile will move in slow-motion opposite of the character's facing direction.

**To Reproduce**
1. Launch the tutorial level.
2. As the plague doctor, throw a projectile.
3. While the attack animation is still playing, change the direction your character is facing.

**Expected behavior**
When changing facing direction, the thrown projectile will be thrown (and move) in that direction.

**Screenshots**
![projectile_matrix](https://user-images.githubusercontent.com/10624460/47806443-2f71c300-dd10-11e8-8e1f-91ad67a3d2f5.gif)

**Comment by StupidChris** [comment]
Possibly fixed in [v0.1.3.18](../releases/v0.1.3.18)

Notes: it is now impossible to turn around while attacking, you can move, but it won't flip around

**Comment by StupidChris** [comment]
Also marking as resolved here
