### ISSUE TITLE
Throwing a projectile while on a slope causes the player to slide down the slope

### ISSUE THREAD

**Issue by TheMelanieJoy** [TeamViral/ViralCurse#62]
**Severity**
Trivial

**Describe the bug**
When the player throws a projectile while on a slope, they will slightly slide down the slope.

**To Reproduce**
1. Launch the tutorial level.
2. As the plague doctor, stand on a slope.
3. Throw a projectile.

**Expected behavior**
The player will not move when throwing projectile.

**Screenshots**
![projectile_slope](https://user-images.githubusercontent.com/10624460/47806786-e66e3e80-dd10-11e8-996d-83ee1579dc8c.gif)

**Comment by StupidChris** [comment]
Possibly fixed in [v0.1.3.18](../releases/v0.1.3.18)

**Comment by StupidChris** [comment]
Gonan close that one myself, pretty sure that's resolved
