### ISSUE TITLE
Background Music Not Playing

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#63]
**Severity**
Minor

**Describe the bug**
When you play the game you don't hear any music, but the other sounds play.

**To Reproduce**
1. Start the game.
2. Press 'Start Game'
3. Listen

**Expected behavior**
I should hear the music.

**Logs**
[Player.log](https://github.com/TeamViral/ViralCurse/files/2535928/Player.log)

**Comment by Jerjerzanne** [comment]
The changes I made to the GameLogic object to have music play were not merged correctly or were reinitialized. 
The music only needs to be remapped.

**Comment by StupidChris** [comment]
Possibly fixed in [v0.1.3.17](../releases/v0.1.3.17)

**Comment by Mottelz** [comment]
It is fixed.
