### ISSUE TITLE
Version Info Never Placed on MacOS

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#64]
**Severity**
Trivial

**Describe the bug**
When Chis asks for the version, I can't find it.

**To Reproduce**
1. Buy a Mac.
2. Build the Game for Mac.
3. Open the package and look for version in the contents.

**Expected behavior**
It should store the version.

**Logs**
[Player.log](https://github.com/TeamViral/ViralCurse/files/2536689/Player.log)

**Additional context**
Seems to be because the version file is set manually and focused on Windows.

**Comment by StupidChris** [comment]
Possibly fixed in [v0.1.3.17](../releases/v0.1.3.17)

**Comment by Mottelz** [comment]
It's fixed
