### ISSUE TITLE
Take a 24 hour nap

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#75]
**Is your feature request related to a problem? Please describe.**
@StupidChris has worked too hard and needs to sleep.

**Describe the solution you'd like**
@StupidChris should go home. Turn off all the devices and sleep until he has work.

**Describe alternatives you've considered**
He could sleep until the Monday afternoon meeting.

**Additional context**
@StupidChris has kicked ass and we're ahead of everyone. Now sleep.

**Comment by TheMelanieJoy** [comment]
Deferred due to me having an assignment due tomorrow morning

**Comment by Mottelz** [comment]
@TheMelanieJoy it's only assigned to Chris.

**Comment by TheMelanieJoy** [comment]
And this is what happens when you only read the title of the issue. In any case, sleep away @StupidChris. @Mottelz will wake you up in 80 hours

**Comment by StupidChris** [comment]
I think the unit is bugged, it automatically turned on the computer and started coding upon returning to original location. Investigating.

**Comment by Mottelz** [comment]
@StupidChris Have you tried turning it off and leaving it that way?

**Comment by StupidChris** [comment]
Managed to keep the unit turned off for a good eight hours, however it's FPU (Food Processing Unit) required attention. Considering as resolved though.
