### ISSUE TITLE
Camera snaps back abruptly after stopping and moving

### ISSUE THREAD

**Issue by Arcavexus** [TeamViral/ViralCurse#79]
**Severity**
Minor

**Describe the bug**
Camera occasionally snaps back to the character as center.

**To Reproduce**
1. Move the character left or right until the camera is moved.
2. Stop moving.
2. Move the character left or right and the camera might snap abruptly to the center of the player.

**Expected behavior**
The camera should not snap back, or at least transition smoothly.

**Screenshots**
https://gyazo.com/6efe1c29152bc4d42dbaa8af0d1b8d8f

**Comment by TheMelanieJoy** [comment]
I've only noticed one occurrence of this during regression. Unless we feel it becomes a really big issue, we can keep this closed. More or less resolved on build v0.3.1.62!
