### ISSUE TITLE
Character Audio

### ISSUE THREAD

**Issue by Jerjerzanne** [TeamViral/ViralCurse#83]
# Character sounds required for Level 1
## List of Character that currently have no audio:
- [x] **Enemy C - [The Spider](https://github.com/TeamViral/ViralCurse/wiki/Enemies#the-spider-c)**
- [x] **Enemy D - [The Puppet](https://github.com/TeamViral/ViralCurse/wiki/Enemies#the-puppet-d)**
- [x] **Enemy E - [The Hammer](https://github.com/TeamViral/ViralCurse/wiki/Enemies#the-hammer-e)**
## Characters that already have audio but could use a second pass:
- [x] **Enemy B - [The Doctor](https://github.com/TeamViral/ViralCurse/wiki/Enemies#the-doctor-b)**
- [x] **Enemy A - [The Rat](https://github.com/TeamViral/ViralCurse/wiki/Enemies#the-rat-a)**
## All characters should have sounds for these common actions:
- **Taking damage**
- **Dying**
- **Walking/Moving**
## All characters will also have two unique actions:
- **main/primary action**
- **alternate/secondary action**  

### Some enemies have projectiles that could have sounds on impact:
- **The Doctor's spear**
- **The Spider's spit/acid**

**Comment by StupidChris** [comment]
Closing this for now, we'll make new issues with updated information down the line when we need a second pass
