### ISSUE TITLE
Environment Audio

### ISSUE THREAD

**Issue by Jerjerzanne** [TeamViral/ViralCurse#84]
## Sounds that have yet to be implemented: 
- [ ] **A unique sound for the player taking damage**
That could just be an effect on that specific character's _''take damage''_ sound or something completely unique. It should be loud or distinct, since the player needs to recognize that sound during combat.
- [x] **Picking up keys**
Keys should have a sound when you pick them up, and it could accompanied by something in the UI.
- [x] **Torch fire crackling**
Torches are currently the main way we bring light to our level. A discrete sound effect could be quite beneficial to the atmosphere.
- [x] **Boss gate opening**
The boss gate is quite larger than the normal gates and require the two keys found in the level. This would play before the player's first encounter with the boss, so you can use this sound to build tension.
- [x] **Text typing sound**
  Current text typing sound is obnoxious. We really need something more generic and theme appropriate.

**Comment by guiray** [comment]
what do you mean by "A unique sound for the player taking damage". Like a sound that will always be the same when the player gets hit?
Or the sound is per character but it's only louder when the player is playing that specific character?

**Comment by Jerjerzanne** [comment]
I want to discuss this issue with @Mottelz, but we can play with unity's audio if we want  to make it louder. I was thinking about a unique sound, but that might be more confusing than helpful for the player. For now, I would recommend that you focus on other issues while we make a decision. Which of these two options makes the most sense to you, @guiray?

**Comment by guiray** [comment]
I think that we will make a better decision when some of the #83 character audio will be done and see how it feels in game. Doing the torch sound and boss gate by the end of the day

**Comment by StupidChris** [comment]
Just as for #83, closing for now.
