### ISSUE TITLE
Boss Audio

### ISSUE THREAD

**Issue by Jerjerzanne** [TeamViral/ViralCurse#85]
# Crucial sounds for the  level 1 boss, [Shomer](https://github.com/TeamViral/ViralCurse/wiki/Bosses#boss-1-shomer):
- [ ] **Taking damage**
- [ ] **Jumping and preparing to jump**
It is important that the player gets familiar with the sounds Shomer makes before taking action. The animation and the sound design should hint at Shomer's next move.
- [ ] **2 sounds for shooting projectiles ( for shooting midair and for lobs)**
- [ ] **Impact sounds for these projectiles**
Projectile impact sound for both the larger lobs of Shomer's main action and the smaller projectiles shot during Shomer's jump.
- [ ] **Dying sound** 
This will mark the end of level 1 and the end of our first polished build, so you can go all out. This will probably play during a scripted sequence/cutscene.
## Optional sounds: 
- [ ] **impact sound of Shomer landing after his jump**
- [ ] **Screams of rage that would happen at different stages of the fight**
As Shomer takes damage, he should become faster, and a signature roar or scream would help the player identify these transitions.

**Comment by guiray** [comment]
is there a visual reference I can look at? either sprite or animation

**Comment by StupidChris** [comment]
Ditto as #83 and 84.
