### ISSUE TITLE
Rat visual bug

### ISSUE THREAD

**Issue by RennXD** [TeamViral/ViralCurse#87]
**Severity**
Minor: Visual bug

**Describe the bug**
When jumping and using ability 2, rat do not always go through the hole. It can go above the rat hole

**To Reproduce**
1. Become a rat.
2. Press jump key then press x key when rat is above the tunnel.
3. The rat goes through into the wall.

**Expected behavior**
Rat should always go through the rat hole and not into the wall.

**Logs**
Please provide the Unity logs create during the run of the game where the issue happened
* Windows: `%UserProfile%\AppData\LocalLow\Team Viral\Viral Curse\output_log.txt`
* macOS: `~/Library/Logs/Unity/Player.log`

**Screenshots**
![ratbug2](https://user-images.githubusercontent.com/26392831/48668069-81596d80-eab2-11e8-9722-6481126bcd3e.png)
![ratbug](https://user-images.githubusercontent.com/26392831/48668071-81596d80-eab2-11e8-899b-57bcade2b138.png)

**Additional context**

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.1.47. Closing out because Renny is being difficult

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.2.2.49
