### ISSUE TITLE
Plague Doctor air born lag time

### ISSUE THREAD

**Issue by RennXD** [TeamViral/ViralCurse#88]
**Severity**

Minor or trivial

**Describe the bug**
When jumping and pressing throwing ability near a wall, the plague doctor stays a big longer in the air.

**To Reproduce**
1. Become a plague doctor
2. When you are next to a wall, press jump key and spam press x key
3. See error

**Expected behavior**
Player should not have more air born time when spamming their throw attack in the wall.

**Logs**
Please provide the Unity logs create during the run of the game where the issue happened
* Windows: `%UserProfile%\AppData\LocalLow\Team Viral\Viral Curse\output_log.txt`
* macOS: `~/Library/Logs/Unity/Player.log`

**Screenshots**
https://gyazo.com/321d313f3d85221fdcbfcd471846844f

**Comment by TheMelanieJoy** [comment]
Resolved on build v0.3.1.62
