### ISSUE TITLE
Text box fades in wrong if NPC speaks first

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#89]
**Severity**
Minor

**Describe the bug**
The dialogue box fades in with the portrait box on the left when an NPC speaks first. It shouldn't.

**To Reproduce**
1. Start the game.
2. Play until an NPC starts the dialogue (After movement in the tutorial opening, for example.)

**Expected behavior**
The dialogue box that will be used should fade in.

**Logs**
[Player.log](https://github.com/TeamViral/ViralCurse/files/2592498/Player.log)

**Screenshots**
![output](https://user-images.githubusercontent.com/5210066/48668454-f0878f80-eabb-11e8-804d-2dd8fae7e6eb.gif)

**Comment by StupidChris** [comment]
Should be fixed now, waiting for test confirmation

**Comment by Mottelz** [comment]
Confirmed fixed. Closing issue.
