### ISSUE TITLE
AI Optimization

### ISSUE THREAD

**Issue by StupidChris** [TeamViral/ViralCurse#93]
Creating a stub here again, for @Jerjerzanne, I just want you to keep track of your progress in here :) Edit this and feel free to list out stuff you need to do.

**Comment by Jerjerzanne** [comment]
### AI changes that were made:
- Doctors cant attack and move at the same time.
- Doctors now have anticipation speed for the first frame.
- Crouch offsets have been moved to serialized fields - will fix soon.

**Comment by Jerjerzanne** [comment]
## AI TODO:
- [ ] Add taunting behavior for the hammer's AI when he deals damage.
- [ ] Boss choreography.

**Comment by StupidChris** [comment]
Closing since the AI will be reworked entirely
