### ISSUE TITLE
Build level 1 in Unity

### ISSUE THREAD

**Issue by StupidChris** [TeamViral/ViralCurse#94]
Another stub, this one for @JeffRayGun. Keep us updated on your work on level one, and maybe make a little checklist or something. I'm tired.

**Comment by JeffRayGun** [comment]
Alright, here's a simple checklist for what will need to be done:

- [ ] Build complete tileset
- [ ] Build in level layout
- [ ] Set colliders

I'm currently waiting on @Arcavexus to add the tiles I asked from him to the tileset before I carry along.

**Comment by StupidChris** [comment]
Finished as well, closing
